version: 2

jobs:
  "golang-1.15":
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install -y zlib1g-dev'
      - run: 'wget https://github.com/DataDog/zstd/files/2246767/mr.zip'
      - run: 'unzip mr.zip'
      - run: 'go build'
      - run: 'PAYLOAD=`pwd`/mr go test -v'
      - run: 'PAYLOAD=`pwd`/mr go test -bench .'
  "golang-1.16":
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install -y zlib1g-dev'
      - run: 'wget https://github.com/DataDog/zstd/files/2246767/mr.zip'
      - run: 'unzip mr.zip'
      - run: 'go build'
      - run: 'PAYLOAD=`pwd`/mr go test -v'
      - run: 'PAYLOAD=`pwd`/mr go test -bench .'
  "golang-latest":
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install -y zlib1g-dev'
      - run: 'wget https://github.com/DataDog/zstd/files/2246767/mr.zip'
      - run: 'unzip mr.zip'
      - run: 'go build'
      - run: 'PAYLOAD=`pwd`/mr go test -v'
      - run: 'PAYLOAD=`pwd`/mr go test -bench .'

workflows:
  version: 2
  build:
    jobs:
      - "golang-1.15"
      - "golang-1.16"
      - "golang-latest"
